// <auto-generated />
namespace MVC4TestBed.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Version01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version01));
        
        string IMigrationMetadata.Id
        {
            get { return "201212232201545_Version01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
